# Generated by Django 5.0.2 on 2024-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=24)),
                ('scope', models.ManyToManyField(to='numman.typeofservice')),
            ],
        ),
    ]
