# Generated by Django 5.0.2 on 2025-09-21 08:14

import django.db.models.deletion
import django.utils.timezone
import numman.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('privileged', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('privileged', models.BooleanField()),
                ('param_type', models.CharField(choices=numman.models.get_types, max_length=3)),
                ('param_length', models.SmallIntegerField()),
                ('param_name', models.CharField(max_length=32)),
                ('group_capable', models.BooleanField(default=False)),
                ('user_data_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4)),
                ('expiry', models.DateTimeField(help_text='Reservation expiry date and time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=4)),
                ('label', models.CharField(max_length=32)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('directory', models.BooleanField(choices=[(True, 'List in Public Phonebook'), (False, 'Not Listed')], default=False)),
                ('param', models.CharField(max_length=32)),
                ('barred', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fwd_number', models.CharField(blank=True, max_length=16)),
                ('user_data', models.JSONField(blank=True, help_text='Additional user data as JSON', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numman.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(to='numman.permission')),
                ('typeofservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numman.typeofservice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='number',
            constraint=models.UniqueConstraint(fields=('event', 'value'), name='unique_event_value'),
        ),
    ]
