# Generated by Django 5.0.2 on 2025-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='fwd_number',
        ),
    ]
